# Usage:
# docker-compose up -d

version: "3"

services:
  reaction:
    build:
      context: .
    depends_on:
      - mongo
    environment:
      ROOT_URL: "http://localhost"
      MONGO_URL: "mongodb://mongo:27017/reaction"
    ports:
      - "80:3000"

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger --bind_ip_all
